<?php

namespace Database\Seeders;

use App\Models\TourPackage;
use App\Models\VisaRequirement;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TourAndVisaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Seed Tour Packages
        $tours = [
            [
                'title' => 'Exotic Thailand Adventure',
                'slug' => 'exotic-thailand-adventure',
                'description' => 'Experience the vibrant culture, stunning beaches, and delicious cuisine of Thailand. Visit Bangkok, Phuket, and Chiang Mai in this comprehensive 7-day tour. Explore ancient temples, enjoy water activities, and indulge in authentic Thai experiences.',
                'itinerary' => "Day 1: Arrival in Bangkok, city tour\nDay 2: Visit Grand Palace and Wat Pho\nDay 3: Flight to Phuket, beach activities\nDay 4: Island hopping tour\nDay 5: Travel to Chiang Mai\nDay 6: Elephant sanctuary visit\nDay 7: Departure",
                'highlights' => 'Grand Palace, Wat Pho Temple, Phuket beaches, Island hopping, Elephant sanctuary, Thai cooking class',
                'price' => 45000.00,
                'currency' => 'BDT',
                'duration_days' => 7,
                'destination' => 'Thailand',
                'departure_location' => 'Dhaka, Bangladesh',
                'max_participants' => 20,
                'min_participants' => 2,
                'is_featured' => true,
                'is_active' => true,
                'included' => 'Hotel accommodation, Breakfast, Airport transfers, English speaking guide, Entrance fees',
                'excluded' => 'International flights, Lunch & Dinner, Personal expenses, Travel insurance',
                'meta_title' => 'Thailand Adventure Tour - 7 Days | Flyover BD',
                'meta_description' => 'Explore Thailand with our 7-day adventure tour. Visit Bangkok, Phuket, and Chiang Mai. Book now!',
            ],
            [
                'title' => 'Dubai Luxury Experience',
                'slug' => 'dubai-luxury-experience',
                'description' => 'Discover the opulence of Dubai with our luxury tour package. Experience world-class shopping, stunning architecture, desert safaris, and iconic landmarks like Burj Khalifa and Palm Jumeirah.',
                'itinerary' => "Day 1: Arrival, Dubai Marina tour\nDay 2: Burj Khalifa visit, Dubai Mall\nDay 3: Desert safari with BBQ dinner\nDay 4: Palm Jumeirah, Atlantis visit\nDay 5: Dubai Museum, Gold Souk\nDay 6: Free day for shopping\nDay 7: Departure",
                'highlights' => 'Burj Khalifa, Desert Safari, Palm Jumeirah, Dubai Mall, Gold Souk, Luxury hotels',
                'price' => 65000.00,
                'currency' => 'BDT',
                'duration_days' => 7,
                'destination' => 'Dubai, UAE',
                'departure_location' => 'Dhaka, Bangladesh',
                'max_participants' => 15,
                'min_participants' => 2,
                'is_featured' => true,
                'is_active' => true,
                'included' => '5-star hotel accommodation, Breakfast, Desert safari, Burj Khalifa tickets, Airport transfers',
                'excluded' => 'International flights, Lunch & Dinner, Shopping expenses, Travel insurance',
                'meta_title' => 'Dubai Luxury Tour - 7 Days | Flyover BD',
                'meta_description' => 'Experience luxury in Dubai with our 7-day tour. Visit iconic landmarks and enjoy world-class hospitality.',
            ],
            [
                'title' => 'Nepal Himalayan Trekking',
                'slug' => 'nepal-himalayan-trekking',
                'description' => 'Embark on an unforgettable trekking adventure in the majestic Himalayas. Experience the natural beauty of Nepal, visit ancient monasteries, and enjoy breathtaking mountain views.',
                'itinerary' => "Day 1: Arrival in Kathmandu\nDay 2: Flight to Pokhara\nDay 3-5: Trekking in Annapurna region\nDay 6: Return to Pokhara\nDay 7: Return to Kathmandu, departure",
                'highlights' => 'Himalayan trekking, Mountain views, Ancient monasteries, Pokhara lakes, Cultural experiences',
                'price' => 35000.00,
                'currency' => 'BDT',
                'duration_days' => 7,
                'destination' => 'Nepal',
                'departure_location' => 'Dhaka, Bangladesh',
                'max_participants' => 12,
                'min_participants' => 2,
                'is_featured' => false,
                'is_active' => true,
                'included' => 'Hotel accommodation, All meals during trek, Trekking guide, Porter service, Permits',
                'excluded' => 'International flights, Personal trekking gear, Travel insurance, Tips',
                'meta_title' => 'Nepal Trekking Tour - 7 Days | Flyover BD',
                'meta_description' => 'Trek through the Himalayas in Nepal. Experience natural beauty and cultural richness.',
            ],
            [
                'title' => 'Malaysia Cultural Tour',
                'slug' => 'malaysia-cultural-tour',
                'description' => 'Explore the diverse culture and stunning landscapes of Malaysia. Visit Kuala Lumpur, Langkawi, and Penang. Experience the perfect blend of modernity and tradition.',
                'itinerary' => "Day 1: Arrival in Kuala Lumpur\nDay 2: City tour, Petronas Towers\nDay 3: Travel to Langkawi\nDay 4: Island activities\nDay 5: Travel to Penang\nDay 6: Cultural tour, food tour\nDay 7: Departure",
                'highlights' => 'Petronas Towers, Langkawi islands, Penang heritage, Malaysian cuisine, Cultural sites',
                'price' => 40000.00,
                'currency' => 'BDT',
                'duration_days' => 7,
                'destination' => 'Malaysia',
                'departure_location' => 'Dhaka, Bangladesh',
                'max_participants' => 18,
                'min_participants' => 2,
                'is_featured' => false,
                'is_active' => true,
                'included' => 'Hotel accommodation, Breakfast, City tours, Airport transfers, Guide',
                'excluded' => 'International flights, Lunch & Dinner, Personal expenses, Travel insurance',
                'meta_title' => 'Malaysia Cultural Tour - 7 Days | Flyover BD',
                'meta_description' => 'Discover Malaysia\'s culture and beauty. Visit KL, Langkawi, and Penang.',
            ],
            [
                'title' => 'Singapore City Break',
                'slug' => 'singapore-city-break',
                'description' => 'Experience the modern marvels of Singapore. Visit iconic attractions like Marina Bay Sands, Gardens by the Bay, Sentosa Island, and enjoy world-class shopping and dining.',
                'itinerary' => "Day 1: Arrival, Marina Bay tour\nDay 2: Gardens by the Bay, Cloud Forest\nDay 3: Sentosa Island\nDay 4: Universal Studios\nDay 5: Orchard Road shopping\nDay 6: Free day\nDay 7: Departure",
                'highlights' => 'Marina Bay Sands, Gardens by the Bay, Sentosa Island, Universal Studios, Shopping',
                'price' => 55000.00,
                'currency' => 'BDT',
                'duration_days' => 7,
                'destination' => 'Singapore',
                'departure_location' => 'Dhaka, Bangladesh',
                'max_participants' => 16,
                'min_participants' => 2,
                'is_featured' => true,
                'is_active' => true,
                'included' => 'Hotel accommodation, Breakfast, Universal Studios tickets, Airport transfers, Guide',
                'excluded' => 'International flights, Lunch & Dinner, Shopping, Travel insurance',
                'meta_title' => 'Singapore City Tour - 7 Days | Flyover BD',
                'meta_description' => 'Explore Singapore\'s modern attractions. Perfect city break experience.',
            ],
            [
                'title' => 'India Golden Triangle',
                'slug' => 'india-golden-triangle',
                'description' => 'Discover India\'s rich heritage with the Golden Triangle tour covering Delhi, Agra, and Jaipur. Visit the iconic Taj Mahal, explore ancient forts, and experience vibrant Indian culture.',
                'itinerary' => "Day 1: Arrival in Delhi\nDay 2: Delhi city tour\nDay 3: Travel to Agra, Taj Mahal visit\nDay 4: Travel to Jaipur\nDay 5: Jaipur city tour, forts\nDay 6: Return to Delhi\nDay 7: Departure",
                'highlights' => 'Taj Mahal, Red Fort, Jaipur Palace, Amber Fort, Indian cuisine, Cultural shows',
                'price' => 38000.00,
                'currency' => 'BDT',
                'duration_days' => 7,
                'destination' => 'India',
                'departure_location' => 'Dhaka, Bangladesh',
                'max_participants' => 20,
                'min_participants' => 2,
                'is_featured' => false,
                'is_active' => true,
                'included' => 'Hotel accommodation, Breakfast, All transfers, Entrance fees, Guide',
                'excluded' => 'International flights, Lunch & Dinner, Personal expenses, Travel insurance',
                'meta_title' => 'India Golden Triangle Tour - 7 Days | Flyover BD',
                'meta_description' => 'Explore India\'s Golden Triangle. Visit Delhi, Agra, and Jaipur.',
            ],
        ];

        foreach ($tours as $tour) {
            TourPackage::create($tour);
        }

        // Seed Visa Requirements
        $visas = [
            [
                'country' => 'United States',
                'country_code' => 'USA',
                'slug' => 'united-states-visa',
                'description' => 'Complete visa assistance for United States tourist, business, and student visas. We provide comprehensive support for all visa types including B1/B2, F1, and H1B visas.',
                'required_documents' => [
                    'Valid passport with at least 6 months validity',
                    'DS-160 confirmation page',
                    'Recent passport-size photographs',
                    'Bank statements (last 6 months)',
                    'Employment letter or business documents',
                    'Travel itinerary',
                    'Hotel reservations',
                    'Previous travel history',
                ],
                'application_guidelines' => "1. Complete DS-160 form online\n2. Pay visa application fee\n3. Schedule interview appointment\n4. Attend visa interview at US Embassy\n5. Wait for visa processing (usually 3-5 business days)",
                'processing_time' => '5-7 business days after interview',
                'visa_fee' => 18500.00,
                'currency' => 'BDT',
                'eligibility_criteria' => 'Applicants must demonstrate strong ties to home country, sufficient financial means, and genuine travel purpose.',
                'important_notes' => 'Visa interview is mandatory. Processing time may vary. Visa approval is at the discretion of the consular officer.',
                'is_active' => true,
                'meta_title' => 'USA Visa Application - Flyover BD',
                'meta_description' => 'Get expert assistance for your US visa application. Complete support for all visa types.',
            ],
            [
                'country' => 'United Kingdom',
                'country_code' => 'GBR',
                'slug' => 'united-kingdom-visa',
                'description' => 'Professional visa services for United Kingdom. We assist with tourist, business, student, and family visit visas. Expert guidance throughout the application process.',
                'required_documents' => [
                    'Valid passport',
                    'Visa application form',
                    'Recent photographs',
                    'Bank statements (last 6 months)',
                    'Employment letter',
                    'Travel itinerary',
                    'Accommodation proof',
                    'Travel insurance',
                ],
                'application_guidelines' => "1. Complete online visa application\n2. Pay visa fee online\n3. Book biometric appointment\n4. Submit documents at VFS Global\n5. Wait for processing (usually 15 working days)",
                'processing_time' => '15 working days (standard)',
                'visa_fee' => 12500.00,
                'currency' => 'BDT',
                'eligibility_criteria' => 'Must show sufficient funds, genuine travel purpose, and intention to return to home country.',
                'important_notes' => 'Biometric appointment is mandatory. Processing time may extend during peak seasons.',
                'is_active' => true,
                'meta_title' => 'UK Visa Application - Flyover BD',
                'meta_description' => 'Expert UK visa assistance. Complete support for tourist, business, and student visas.',
            ],
            [
                'country' => 'United Arab Emirates',
                'country_code' => 'ARE',
                'slug' => 'united-arab-emirates-visa',
                'description' => 'Fast and reliable UAE visa services. We process tourist, transit, and business visas for Dubai, Abu Dhabi, and other Emirates. Quick processing available.',
                'required_documents' => [
                    'Valid passport (minimum 6 months validity)',
                    'Passport-size photograph',
                    'Completed application form',
                    'Flight booking confirmation',
                    'Hotel reservation',
                    'Bank statement',
                ],
                'application_guidelines' => "1. Submit required documents\n2. Pay visa fee\n3. Application processing (2-5 business days)\n4. Receive e-visa via email\n5. Print and carry e-visa for travel",
                'processing_time' => '2-5 business days',
                'visa_fee' => 8500.00,
                'currency' => 'BDT',
                'eligibility_criteria' => 'Valid passport, confirmed travel bookings, and sufficient financial means required.',
                'important_notes' => 'E-visa is issued electronically. Processing is faster for standard applications.',
                'is_active' => true,
                'meta_title' => 'UAE Visa Application - Flyover BD',
                'meta_description' => 'Quick UAE visa processing. Tourist, transit, and business visas available.',
            ],
            [
                'country' => 'Canada',
                'country_code' => 'CAN',
                'slug' => 'canada-visa',
                'description' => 'Comprehensive Canada visa services including tourist, business, and study permits. Expert guidance for TRV (Temporary Resident Visa) applications.',
                'required_documents' => [
                    'Valid passport',
                    'Visa application forms',
                    'Recent photographs',
                    'Bank statements (last 6 months)',
                    'Employment letter',
                    'Travel itinerary',
                    'Purpose of visit letter',
                    'Travel insurance',
                ],
                'application_guidelines' => "1. Complete online application\n2. Pay visa fee\n3. Submit biometrics at VAC\n4. Submit passport and documents\n5. Wait for processing (15-30 days)",
                'processing_time' => '15-30 business days',
                'visa_fee' => 14500.00,
                'currency' => 'BDT',
                'eligibility_criteria' => 'Must demonstrate strong ties to home country, financial stability, and genuine travel purpose.',
                'important_notes' => 'Biometric collection is mandatory. Processing time varies by application type.',
                'is_active' => true,
                'meta_title' => 'Canada Visa Application - Flyover BD',
                'meta_description' => 'Expert Canada visa assistance. Tourist, business, and study permits available.',
            ],
            [
                'country' => 'Australia',
                'country_code' => 'AUS',
                'slug' => 'australia-visa',
                'description' => 'Professional Australia visa services for tourist, business, and student visas. We provide complete support for all visa subclasses including visitor visas (600) and student visas (500).',
                'required_documents' => [
                    'Valid passport',
                    'Visa application form',
                    'Recent photographs',
                    'Bank statements',
                    'Employment proof',
                    'Travel itinerary',
                    'Health insurance',
                    'Character documents',
                ],
                'application_guidelines' => "1. Create ImmiAccount\n2. Complete online application\n3. Upload required documents\n4. Pay visa fee\n5. Wait for processing (15-30 days)",
                'processing_time' => '15-30 business days',
                'visa_fee' => 16500.00,
                'currency' => 'BDT',
                'eligibility_criteria' => 'Must meet health and character requirements, show sufficient funds, and genuine travel purpose.',
                'important_notes' => 'Online application through ImmiAccount. Processing time may vary.',
                'is_active' => true,
                'meta_title' => 'Australia Visa Application - Flyover BD',
                'meta_description' => 'Complete Australia visa services. Tourist, business, and student visas.',
            ],
            [
                'country' => 'Thailand',
                'country_code' => 'THA',
                'slug' => 'thailand-visa',
                'description' => 'Easy and quick Thailand visa processing. We handle tourist visas, business visas, and visa on arrival services. Fast processing available.',
                'required_documents' => [
                    'Valid passport (6 months validity)',
                    'Passport-size photographs',
                    'Completed application form',
                    'Flight booking',
                    'Hotel reservation',
                    'Bank statement',
                ],
                'application_guidelines' => "1. Submit application with documents\n2. Pay visa fee\n3. Processing (3-5 business days)\n4. Collect visa\n5. Ready to travel",
                'processing_time' => '3-5 business days',
                'visa_fee' => 3500.00,
                'currency' => 'BDT',
                'eligibility_criteria' => 'Valid passport and confirmed travel bookings required.',
                'important_notes' => 'Visa on arrival also available at airports. Tourist visa valid for 60 days.',
                'is_active' => true,
                'meta_title' => 'Thailand Visa Application - Flyover BD',
                'meta_description' => 'Quick Thailand visa processing. Tourist and business visas available.',
            ],
            [
                'country' => 'Malaysia',
                'country_code' => 'MYS',
                'slug' => 'malaysia-visa',
                'description' => 'Simple Malaysia visa application process. We assist with tourist visas and e-visa applications. Fast and reliable service.',
                'required_documents' => [
                    'Valid passport',
                    'Passport photograph',
                    'Flight booking',
                    'Hotel reservation',
                    'Bank statement',
                ],
                'application_guidelines' => "1. Complete online application\n2. Upload documents\n3. Pay visa fee\n4. Receive e-visa (2-3 days)\n5. Print e-visa for travel",
                'processing_time' => '2-3 business days',
                'visa_fee' => 3000.00,
                'currency' => 'BDT',
                'eligibility_criteria' => 'Valid passport and travel bookings required.',
                'important_notes' => 'E-visa available online. Processing is quick and efficient.',
                'is_active' => true,
                'meta_title' => 'Malaysia Visa Application - Flyover BD',
                'meta_description' => 'Easy Malaysia visa processing. E-visa services available.',
            ],
            [
                'country' => 'Singapore',
                'country_code' => 'SGP',
                'slug' => 'singapore-visa',
                'description' => 'Efficient Singapore visa services. We process tourist and business visas with quick turnaround times. Expert assistance throughout.',
                'required_documents' => [
                    'Valid passport (6 months validity)',
                    'Recent photographs',
                    'Completed application form',
                    'Flight booking',
                    'Hotel reservation',
                    'Bank statements',
                    'Employment letter',
                ],
                'application_guidelines' => "1. Submit application online or in-person\n2. Pay visa fee\n3. Processing (3-5 business days)\n4. Receive visa\n5. Ready to travel",
                'processing_time' => '3-5 business days',
                'visa_fee' => 4500.00,
                'currency' => 'BDT',
                'eligibility_criteria' => 'Valid passport, confirmed bookings, and sufficient funds required.',
                'important_notes' => 'Visa processing is usually quick. Multiple entry visas available.',
                'is_active' => true,
                'meta_title' => 'Singapore Visa Application - Flyover BD',
                'meta_description' => 'Quick Singapore visa processing. Tourist and business visas.',
            ],
        ];

        foreach ($visas as $visa) {
            VisaRequirement::create($visa);
        }

        $this->command->info('Successfully seeded ' . count($tours) . ' tours and ' . count($visas) . ' visa requirements!');
    }
}

